-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE airport (
    id SERIAL PRIMARY KEY,
    ident text,
    type text,
    name text,
    elevation_ft integer,
    continent text,
    iso_country text,
    iso_region text,
    municipality text,
    scheduled_service character varying,
    gps_code character varying,
    iata_code character varying,
    local_code character varying,
    home_link text,
    wikipedia_link text,
    keywords text,
    geom geometry
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX airport_pkey ON airport(id int4_ops);
