-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE flight_operator (
    id SERIAL PRIMARY KEY,
    name text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX flight_operator_pkey ON flight_operator(id int4_ops);
