-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE flight (
    id SERIAL PRIMARY KEY,
    airport_departure_link_id integer REFERENCES airport(id),
    airport_arrival_link_id integer REFERENCES airport(id),
    geom geometry,
    datetime_departure timestamp without time zone,
    datetime_arrival timestamp without time zone,
    operator_link_id integer REFERENCES flight_operator(id),
    code text,
    status text DEFAULT 'completed'::text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX flight_pkey ON flight(id int4_ops);
