-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE trips (
    id SERIAL PRIMARY KEY,
    name text,
    description text,
    country_codes text,
    header_image_url text,
    active boolean,
    extent geometry
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX trips_pkey ON trips(id int4_ops);
