-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE trip_segment (
    id SERIAL PRIMARY KEY,
    trip_id integer REFERENCES trips(id),
    location_type text,
    name text,
    long_description text,
    arrival_time timestamp with time zone,
    departure_time timestamp with time zone,
    short_description text,
    accommodation_id integer REFERENCES accommodation(id),
    posted_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    location_text text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX trip_segment_pkey ON trip_segment(id int4_ops);
